### ISSUE TITLE
Check whether to build with UA_INLINABLE_EXPORT 

### ISSUE THREAD

**Issue by thomvet** [martinkosch/Open62541.jl#16]
While adapting the generator script for v1.4, I discovered the following: 
https://github.com/open62541/open62541/blob/043af7d279778eceed82d83fc2737a04acaa2389/include/open62541/config.h.in#L178

It seems hat open62541 has added a possibility to export inlined functions; it's not (yet) mentioned in the documentation, but visible in the code.

Could be that this is a way to get rid of a lot of code generation in open62541.jl.

**Comment by martinkosch** [comment]
Nice! Apparently this functionality was recently added in a PR (https://github.com/open62541/open62541/pull/5926). Do you expect any drawbacks when turning the `UA_ENABLE_INLINABLE_EXPORT` flag on in the binary?

**Comment by thomvet** [comment]
From the open62541 config file: https://github.com/open62541/open62541/blob/043af7d279778eceed82d83fc2737a04acaa2389/include/open62541/config.h.in#L170

"Note that UA_ENABLE_INLINABLE_EXPORT has a negative impact for both size and performance of the library."

Size is not relevant here given that Julia is huge on its own already (let's not worry about adding a bucket of sand to a beach) and small Julia binaries are still some distance away in the future.

The performance part is, i don't know!

**Comment by thomvet** [comment]
I tested this through and it's limited to a async functions and a few of the basic functions like UA_STRING etc; other inlined functions (such as node additions and UA_String_new()) are still not exported. 

Some of the ones that get exported are unfortunately confusing the memory management part of the package (example UA_STRING returns a UA_String, not the respective pointer); then one is left with not knowing whether Julia manages the memory or C.

Therefore, for the time being, I don't think this makes sense to use when building the binary package.
