### ISSUE TITLE
User-facing API

### ISSUE THREAD

**Issue by thomvet** [martinkosch/open62541.jl#9]
At the moment everything with a `UA_` and with a `__UA_` at the start of the name is exported. In Julia packages typically all exported names are seen as API (unless specifically stated otherwise, maybe in a docstring?). That's a huge surface area and any change of existing behavior on it would technically be a breaking change (unless it's a bug :)).

It would be good to consider what we actually see as "the API".

My viewpoint is that we should be quite conscious on it and start with a small surface area (e.g., things we actually test and know that they work). I would prefer providing high-level functionality over low level granularity as API. (the lower level things are still there, just would need a `open62541.XXX` instead of `XXX`)

**Comment by thomvet** [comment]
I broadly agree with these thoughts. 
But it would also like to consider whether it makes sense to emit more general methods (that are easy to remember) using dispatch on types rather than very specific methods. For example, we currently have methods like:
```
UA_String_delete(...)
UA_NodeId_delete(...)
```
Etc. (for all 200+ types in open62541). We could consider to have a more general method in Julia that safely deletes an object, whatever it is (and under the hood calls the correct function or the more general `UA_delete()` function. So, for example, we would have one function with multiple methods and dispatch on the relevant types:
```
UA_delete(x::UA_String)
UA_delete(x::UA_NodeId)
```
In C the functions are separated out to make them specific and fast (no multiple dispatch), but in Julia we could just use multiple dispatch to keep the interface simple?

That would simplify what the user has to remember for things like `UA_XXX_delete`, `UA_XXX_copy`, `UA_XXX_clear`, etc. (It wouldn't address the "UA_NodeId_new()" type of functions, though).

Thoughts? :)

**Comment by martinkosch** [comment]
Yes, this is a good plan, at least for all the basic functions except for `UA_...new()`. It should be a matter of a few lines each. 
The only alternative to `UA_..._new()` would be to use the usual Julia convention for constructors, namely the same function names without `_new`. However, I am not sure if this puts enough emphasis on the need to free the allocated memory afterwards. 
Maybe it is best to keep all original function names (`UA_XXX_new`, `UA_XXX_delete`, `UA_XXX_copy`, `UA_XXX_clear,...) to comply with the original library and add additional convenience methods without the specific type names in uncritical cases.

**Comment by thomvet** [comment]
Broadly speaking, I think we should keep the interface as is right now with the high level functions (JUA...) and the original open62541 interface (UA...) exported alongside each other and should move towards registering the package. If breaking changes become necessary, it will have to be considered again.
